// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0

// Resolution order:
// 1. VITE_* environment variables (highest priority)
// 2. config.json (generated by install.js from CloudFormation outputs)
// 3. config.example.json (committed defaults pointing to mock server)

let configValues = {}

const modules = import.meta.glob(['./config.json', './config.example.json'], { eager: true })

if (modules['./config.json']) {
  const config = modules['./config.json'].default || modules['./config.json']
  config[0].forEach(item => {
    configValues[item.OutputKey] = item.OutputValue
  })
} else if (modules['./config.example.json']) {
  const config = modules['./config.example.json'].default || modules['./config.example.json']
  config[0].forEach(item => {
    configValues[item.OutputKey] = item.OutputValue
  })
  console.info('[config] Using config.example.json (mock/local mode)')
} else {
  console.warn('[config] No config file found. Set VITE_* env vars or run the mock server.')
}

function getConfigValue(outputKey, envKey) {
  return import.meta.env[envKey] || configValues[outputKey] || ''
}

export const GET_RECORDING_API = getConfigValue('ApiURLGetRecordings', 'VITE_API_RECORDINGS')
export const GET_CLIPS_API = getConfigValue('ApiURLGetClips', 'VITE_API_CLIPS')
export const POST_CLIPMANIFEST_API = getConfigValue('ApiURLCreateClip', 'VITE_API_CLIPMANIFEST')

export function getFullConfig() {
  const keys = Object.keys(configValues)
  if (keys.length === 0) return null
  return [keys.map(key => ({ OutputKey: key, OutputValue: getConfigValue(key, `VITE_${key}`) }))]
}
