// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0

// Resolution order:
// 1. REACT_APP_* environment variables (highest priority)
// 2. config.json (generated by install.js from CloudFormation outputs)
// 3. config.example.json (committed defaults pointing to mock server)

let configValues = {}

try {
  const config = require('./config.json')
  config[0].forEach(item => {
    configValues[item.OutputKey] = item.OutputValue
  })
} catch {
  try {
    const config = require('./config.example.json')
    config[0].forEach(item => {
      configValues[item.OutputKey] = item.OutputValue
    })
    console.info('[config] Using config.example.json (mock/local mode)')
  } catch {
    console.warn('[config] No config file found. Set REACT_APP_* env vars or run the mock server.')
  }
}

function getConfigValue(outputKey, envKey) {
  return process.env[envKey] || configValues[outputKey] || ''
}

export const GET_RECORDING_API = getConfigValue('ApiURLGetRecordings', 'REACT_APP_API_RECORDINGS')
export const GET_CLIPS_API = getConfigValue('ApiURLGetClips', 'REACT_APP_API_CLIPS')
export const POST_CLIPMANIFEST_API = getConfigValue('ApiURLCreateClip', 'REACT_APP_API_CLIPMANIFEST')

export function getFullConfig() {
  const keys = Object.keys(configValues)
  if (keys.length === 0) return null
  return [keys.map(key => ({ OutputKey: key, OutputValue: getConfigValue(key, `REACT_APP_${key}`) }))]
}
