#!/usr/bin/env bash
# Fetches CloudFormation outputs for the serverless backend stack
# and writes them to test.conf for use by test scripts.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_FILE="${SCRIPT_DIR}/test.conf"
EXAMPLE_FILE="${SCRIPT_DIR}/test.conf.example"

# Load existing conf or fall back to example for STACK_NAME / REGION
if [[ -f "$CONF_FILE" ]]; then
  source "$CONF_FILE"
elif [[ -f "$EXAMPLE_FILE" ]]; then
  source "$EXAMPLE_FILE"
fi

STACK_NAME="${STACK_NAME:-clip-manifest-ui}"
AWS_REGION="${AWS_REGION:-us-east-1}"

echo "Fetching outputs from stack: ${STACK_NAME} (${AWS_REGION})..."

OUTPUTS=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$AWS_REGION" \
  --query "Stacks[0].Outputs" \
  --output json 2>&1)

if [[ $? -ne 0 ]]; then
  echo "Error: Failed to describe stack. Are your credentials valid?"
  echo "$OUTPUTS"
  exit 1
fi

get_output() {
  echo "$OUTPUTS" | python3 -c "
import sys, json
outputs = json.load(sys.stdin)
for o in outputs:
    if o['OutputKey'] == '$1':
        print(o['OutputValue'])
        break
" 2>/dev/null || echo ""
}

API_RECORDINGS=$(get_output ApiURLGetRecordings)
API_CLIPS=$(get_output ApiURLGetClips)
API_CLIPMANIFEST=$(get_output ApiURLCreateClip)
CLOUDFRONT_DOMAIN=$(get_output CloudfrontDistribution)
S3_BUCKET=$(get_output RecordConfigurationBucket)
SAMPLE_MASTER_URL=$(get_output SampleRecordingMasterURL)

cat > "$CONF_FILE" <<EOF
# Serverless Backend Test Configuration
# Auto-generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

STACK_NAME="${STACK_NAME}"
AWS_REGION="${AWS_REGION}"

# CloudFormation outputs
API_RECORDINGS="${API_RECORDINGS}"
API_CLIPS="${API_CLIPS}"
API_CLIPMANIFEST="${API_CLIPMANIFEST}"
CLOUDFRONT_DOMAIN="${CLOUDFRONT_DOMAIN}"
S3_BUCKET="${S3_BUCKET}"

# Test parameters
MASTER_URL="${SAMPLE_MASTER_URL:-${CLOUDFRONT_DOMAIN}/ivs/v1/ACCOUNT/CHANNEL/YYYY/MM/DD/HH/mm/RECORDING_ID/media/hls/master.m3u8}"
START_TIME=2
END_TIME=8
BYTE_RANGE=false
EOF

echo ""
echo "Configuration written to: ${CONF_FILE}"
echo ""
echo "  API_RECORDINGS:  ${API_RECORDINGS}"
echo "  API_CLIPS:       ${API_CLIPS}"
echo "  API_CLIPMANIFEST: ${API_CLIPMANIFEST}"
echo "  CLOUDFRONT:      ${CLOUDFRONT_DOMAIN}"
echo "  S3_BUCKET:       ${S3_BUCKET}"
echo "  MASTER_URL:      ${SAMPLE_MASTER_URL:-"(not set — update test.conf manually)"}"
