version = 0.1

[default.deploy.parameters]
stack_name = "ivs-rt-recorder"
resolve_s3 = true
s3_prefix = "ivs-rt-recorder"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
