version = 0.1
[default.deploy.parameters]
stack_name = "ivs-clip-manifest-standalone"
resolve_s3 = true
s3_prefix = "ivs-clip-manifest-standalone"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
