version = 0.1
[default.deploy.parameters]
stack_name = "clip-manifest-ui"
resolve_s3 = true
s3_prefix = "clip-manifest-ui"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
