#!/usr/bin/env bash
# Fetches CloudFormation outputs for the standalone API stack
# and writes them to test.conf for use by test scripts.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_FILE="${SCRIPT_DIR}/test.conf"
EXAMPLE_FILE="${SCRIPT_DIR}/test.conf.example"

# Load existing conf or fall back to example for STACK_NAME / REGION
if [[ -f "$CONF_FILE" ]]; then
  source "$CONF_FILE"
elif [[ -f "$EXAMPLE_FILE" ]]; then
  source "$EXAMPLE_FILE"
fi

STACK_NAME="${STACK_NAME:-ivs-clip-manifest-standalone}"
AWS_REGION="${AWS_REGION:-us-west-2}"

echo "Fetching outputs from stack: ${STACK_NAME} (${AWS_REGION})..."

OUTPUTS=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$AWS_REGION" \
  --query "Stacks[0].Outputs" \
  --output json 2>&1)

if [[ $? -ne 0 ]]; then
  echo "Error: Failed to describe stack. Are your credentials valid?"
  echo "$OUTPUTS"
  exit 1
fi

API_URL=$(echo "$OUTPUTS" | python3 -c "
import sys, json
outputs = json.load(sys.stdin)
for o in outputs:
    if o['OutputKey'] == 'ApiURLCreateClip':
        print(o['OutputValue'])
        break
")

CLOUDFRONT_DOMAIN=$(echo "$OUTPUTS" | python3 -c "
import sys, json
outputs = json.load(sys.stdin)
for o in outputs:
    if o['OutputKey'] == 'CloudfrontDistribution':
        print(o['OutputValue'])
        break
")

S3_BUCKET=$(echo "$OUTPUTS" | python3 -c "
import sys, json
outputs = json.load(sys.stdin)
for o in outputs:
    if o['OutputKey'] == 'RecordConfiguration':
        print(o['OutputValue'])
        break
")

SAMPLE_MASTER_URL=$(echo "$OUTPUTS" | python3 -c "
import sys, json
outputs = json.load(sys.stdin)
for o in outputs:
    if o['OutputKey'] == 'SampleRecordingMasterURL':
        print(o['OutputValue'])
        break
" 2>/dev/null || echo "")

cat > "$CONF_FILE" <<EOF
# Standalone API Test Configuration
# Auto-generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

STACK_NAME="${STACK_NAME}"
AWS_REGION="${AWS_REGION}"

# CloudFormation outputs
API_URL="${API_URL}"
CLOUDFRONT_DOMAIN="${CLOUDFRONT_DOMAIN}"
S3_BUCKET="${S3_BUCKET}"

# Test parameters — adjust to match a real recording in your bucket
MASTER_URL="${SAMPLE_MASTER_URL:-${CLOUDFRONT_DOMAIN}/ivs/v1/ACCOUNT/CHANNEL/YYYY/MM/DD/HH/mm/RECORDING_ID/media/hls/master.m3u8}"
START_TIME=2
END_TIME=8
BYTE_RANGE=false
EOF

echo ""
echo "Configuration written to: ${CONF_FILE}"
echo ""
echo "  API_URL:           ${API_URL}"
echo "  CLOUDFRONT_DOMAIN: ${CLOUDFRONT_DOMAIN}"
echo "  S3_BUCKET:         ${S3_BUCKET}"
echo ""
echo "Edit test.conf to set MASTER_URL to a real recording before running tests."
